backend:
  name: git-gateway
  branch: main # <--- Verifica che su GitHub il tuo branch si chiami 'main'

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Post"
    folder: "Blog"
    create: true
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }